### ISSUE TITLE
Tremor panics at Influx codec decode if the input data ends with an odd number of escape ('\') characters  

### ISSUE THREAD

**Issue by anuprout** [wayfair-tremor/tremor-runtime#294]
**Problem**

Tremor panics with the below error while decoding the input data with Influx codec if the data ends with an odd number of escape character . Ex - "\", "\\\", "xyz\"  etc. 

```
thread 'onramp-udp-???' panicked at 'byte index 1 is out of bounds of ``', src/libcore/str/mod.rs:2196:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::str::slice_error_fail
             at src/libcore/str/mod.rs:2196
  14: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/str/mod.rs:1986
  15: core::option::Option<T>::unwrap_or_else
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/option.rs:428
  16: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/str/mod.rs:1986
  17: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/str/mod.rs:1780
  18: tremor_influx::decoder::parse_to_complex
             at /Users/ar862t/tremor-runtime/tremor-influx/src/decoder.rs:312
  19: tremor_influx::decoder::parse_to
             at /Users/ar862t/tremor-runtime/tremor-influx/src/decoder.rs:280
  20: tremor_influx::decoder::decode
             at /Users/ar862t/tremor-runtime/tremor-influx/src/decoder.rs:42
  21: <tremor_runtime::codec::influx::Influx as tremor_runtime::codec::Codec>::decode::{{closure}}
             at src/codec/influx.rs:67
  22: tremor_script::rentals::Value::try_new
             at /Users/ar862t/tremor-runtime/<::rental::rental macros>:30
  23: <tremor_runtime::codec::influx::Influx as tremor_runtime::codec::Codec>::decode
             at src/codec/influx.rs:61
  24: tremor_runtime::onramp::prelude::send_event
             at src/onramp/prelude.rs:81
  25: tremor_runtime::onramp::udp::onramp_loop
             at src/onramp/udp.rs:108
  26: <tremor_runtime::onramp::udp::Udp as tremor_runtime::onramp::Onramp>::start::{{closure}}
             at src/onramp/udp.rs:147_
```

The code **"tremor-influx/src/decoder.rs:312"** tries to get a slice of the input data even after reaching the end of the input string causing the error.

**Steps**

1. start Tremor with Influx codec for the onramp
2. send any of  the below payloads  to onramp 
"some data **\\**" 
"some data **\\\\\\**" 
"some data **\\\\\\\\\\**" 

**Possible Solution(s)**

Put a check to see if the end of the input string has been reached. 
```
if input.len() != 0 {
	  res.push_str(&input[..1]);
          input = &input[1..];
 }

```
**Notes**

Output of `rustup --version`:
Output of `rustup show`:
Output of `tremor-server --version`: 0.8.0

**Comment by Licenser** [comment]
Good catch!

Do you want to take a crack at it? Otherwise we'll put it on the fast track for fixing :)
